name: Build and publish
on: [push]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set APP_VERSION env
      run: echo APP_VERSION=1.0.1 >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
