  build-go-binary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.4'

      - name: Run a multi-line script
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build
          mv gitlab_ci_vars_lint binaries/
      - uses: actions/upload-artifact@master
        with:
          path: ./binaries/gitlab_ci_vars_lint
