name: Build and publish
on: [push]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.4'

      - name: Run a multi-line script
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build
      - uses: actions/upload-artifact@master
        with:
          path: ./gitlab_ci_vars_lint

  push_go_binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

