name: Build and publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:alpine3.17
      volumes:
        - $(pwd):/files
    steps:
      - uses: actions/checkout@v3
      #- name: Setup Go
        #uses: actions/setup-go@v3
        #with:
          #go-version: '1.19.x'
      - name: go get && go build
        run: cd /files; go get . && go build -o ./binaries/ && md5sum ./binaries/gitlab_ci_vars_lint 2>/dev/null
  push_binary:
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Commit files
        run: |
          git config --local user.email "gregs+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
